---
- name: Open ports for firewall if variable false
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  with_items:
    - 179/tcp
    - 4789/udp
    - 4/tcp
    - 5473/tcp
  when: not disable_firewall

- name: Add masquerade for public zone firewalld
  firewalld:
    permanent: yes
    state: enabled
    immediate: yes
    masquerade: yes
    zone: public
  when: not disable_firewall
